version: "3"

tasks:
  build-wasm:
    desc: "Build the Go code to WebAssembly"
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o build/app.wasm main.go
      - cp $(go env GOROOT)/lib/wasm/wasm_exec.js web/assets/wasm_exec.js
      - base64 -i build/app.wasm -o build/app.wasm.base64
      - ./web/scripts/export_wasm.sh build/app.wasm.base64

  build-wasm:cleanup:
    desc: "Cleanup after build"
    cmds:
      - rm -rf build

  clean:
    desc: "Clean the build files"
    cmds:
      - rm -rf build
      - rm -f assetes/wasmexprt.js web/assets/wasm_exec.js

  build:
    desc: "Build the project"
    cmds:
      - task: clean
      - task: build-wasm
      - task: build-wasm:cleanup
